check:
  image: nixpkgs/nix-flakes
  script:
    - nix flake check

build:
  image: nixpkgs/nix-flakes
  script:
    - nix build .#omega-star
    # - mkdir -p "/etc/containers/"
    # - echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
    - nix develop
    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    # - ls -lh ./result
    - 'skopeo inspect docker-archive://$(readlink -f ./result)'
    - 'skopeo copy docker-archive://$(readlink -f ./result) docker://$IMAGE_TAG'
