build:
  image: nixpkgs/nix-flakes
  script:
    - tag=$(date +%s)
    - mkdir -p "/var/tmp/"
    - nix develop --command skopeo login --username "$SFZ_REGISTRY_USER" --password "$SFZ_REGISTRY_PASSWORD" "$SFZ_REGISTRY"
