CREATE TABLE menus (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS menu_items (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    short_name VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    menu_id INTEGER NOT NULL,
    price INTEGER NOT NULL,
    FOREIGN KEY(menu_id) REFERENCES menus(id) ON UPDATE CASCADE ON DELETE CASCADE
);
