package entity

import "errors"

var (
	ErrCannotCreatUuid = errors.New("cannot create uuid")
	ErrCannotGetAllOrder = errors.New("could not get all orders from db")
	ErrOrderNotFound = errors.New("order not found")
	ErrGettingOrder = errors.New("could not get order from db")
	ErrCannotGetAllOrders = errors.New("could not get all order items from db")
	ErrGettingOrderItem = errors.New("error getting order item")
	ErrOrderItemNotFound = errors.New("order item not found")
	ErrCreatingOrderItem = errors.New("could not create order item")
	ErrOrderNotOpen = errors.New("order is not in state open")
	ErrMenuItemUuidMissing = errors.New("menu item uuid missing")
	ErrCreatingOrder = errors.New("could not create order")
	ErrActiveOrderForMenuAlreadyExists = errors.New("there is already an active order the specified menu")
	ErrUpdatingOrder = errors.New("could not update order")
	ErrSugarPersonChangeForbidden = errors.New("changing sugar person after it has already been set is forbidden")
	ErrOrderStateTransitionInvalid = errors.New("invalid order state transition")
	ErrUpdatingOrderItem = errors.New("could not update order item")
	ErrDeletingOrderItem = errors.New("could not delete order item")
	ErrCannotGetAllUsers = errors.New("could not get all users from db")
	ErrGettingUser = errors.New("failed to get user")
	ErrUserNotFound = errors.New("user not found")
	ErrCreatingUser = errors.New("could not create user")
	ErrUpdatingUser = errors.New("could not update users")
	ErrDeletingUser = errors.New("could not delete user")
	ErrCannotGetAllMenus = errors.New("could not get all menus from db")
	ErrGettingMenu = errors.New("failed to get menu")
	ErrMenuNotFound = errors.New("menu not found")
	ErrGettingMenuItem = errors.New("failed to get menu item")
	ErrMenuItemNotFound = errors.New("menu item not found")
	ErrCreatingMenu = errors.New("could not create menu")
	ErrUpdatingMenu = errors.New("could not update menu")
	ErrCreatingMenuItem = errors.New("could not create menu item")
	ErrDeletingMenuItem = errors.New("could not delete menu item")
	ErrDeletingMenu = errors.New("could not delete menu")
	ErrMigrationPreparationFailed = errors.New("database migration preparation failed")
	ErrMigrationFailed = errors.New("database migration execution failed")
)

