CREATE TABLE IF NOT EXISTS menu_items (
    menu VARCHAR(255) NOT NULL,
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    FOREIGN KEY(menus) REFERENCES menu(name) ON UPDATE CASCADE
);
