CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(40) NOT NULL
);

CREATE TABLE orders (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    order_deadline INTEGER,
    eta INTEGER,
    initiator INTEGER NOT NULL,
    sugar_person INTEGER,
    state VARCHAR(40) NOT NULL,
    FOREIGN KEY(initiator) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(sugar_person) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE order_items (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    menu_item_id INTEGER NOT NULL,
    user INTEGER NOT NULL,
    paid BOOLEAN NOT NULL,
    order_id INTEGER NOT NULL,
    FOREIGN KEY(menu_item_id) REFERENCES menu_items(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(order_id) REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE
);
